#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export VISUAL=$(which vim)
export EDITOR=$VISUAL
export FCEDIT=$VISUAL

export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# From old .zshenv

export PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache

[ -d $HOME/bin ] && export PATH=$HOME/bin:$PATH

# Add git if installed on Mac
# Interactive only, to make sure that it doesn't interfere with Xcode
[[ -o interactive ]] && [ -x /usr/local/git/bin/git ] && export PATH=/usr/local/git/bin:$PATH

# CVS
export CVSROOT=:pserver:kam@cvs.dlogics.com:/dl/cvsroot

[ -d $HOME/src/dl ] && cdpath+=($HOME/src/dl)
[ -d $HOME/src ] && cdpath+=($HOME/src)
